apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: obelisk
  namespace: '298930680646'
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    serving.knative.dev/creator: kushagra9nov@gmail.com
    serving.knative.dev/lastModifier: kushagra9nov@gmail.com
    run.googleapis.com/client-name: cloud-console
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/invoker-iam-disabled: 'true'
spec:
  template:
    metadata:
      labels:
        client.knative.dev/nonce: updated-deployment
        run.googleapis.com/startupProbeType: Default
      annotations:
        run.googleapis.com/client-name: cloud-console
        autoscaling.knative.dev/maxScale: '3'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 600
      serviceAccountName: 298930680646-compute@developer.gserviceaccount.com
      containers:
      - name: obelisk-1
        image: kshgrk/obelisk:cloudrun-v2
        ports:
        - name: http1
          containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 8080
  traffic:
  - percent: 100
    latestRevision: true
