version: '3.8'

services:
  # Temporal Server
  temporal:
    image: temporalio/auto-setup:1.25.0
    container_name: obelisk-temporal
    ports:
      - "7233:7233"  # gRPC
      - "8233:8233"  # Web UI
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
    volumes:
      - ./temporal-config:/etc/temporal/config/dynamicconfig
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - temporal-network

  # PostgreSQL Database for Temporal
  postgresql:
    image: postgres:15
    container_name: obelisk-temporal-db
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
      POSTGRES_DB: temporal
    ports:
      - "5432:5432"
    volumes:
      - temporal-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U temporal"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - temporal-network

  # Temporal Web UI (optional, for better UI experience)
  temporal-ui:
    image: temporalio/ui:2.28.0
    container_name: obelisk-temporal-ui
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    ports:
      - "8080:8080"
    networks:
      - temporal-network

volumes:
  temporal-postgres-data:

networks:
  temporal-network:
    driver: bridge 